### PR TITLE
RxJava3: Ports EffectHandlerException class and test

### PR DESCRIPTION
**Pull request by amilcar-andrade**

### CODE REVIEW

**Comment by amilcar-andrade** [comment]
@pettermahlen I missed your new functionality when doing the initial pull request for rxjava3, I just did the port here.

**Comment by pettermahlen** [comment]
I noticed that, that's fine, I wanted to see how that functionality actually behaves when it hits firebase before adding it to Rx3 as well. Thanks for the PR, once we've got it working well for Rx2, we can merge this too.

**Comment by amilcar-andrade** [comment]
@pettermahlen any update on this?

**Comment by amilcar-andrade** [comment]
Closing, seems this is/was not that important to port over

**Pull request closed without merging**
