### PR TITLE
RxMobius: Removes unused SchedulerWorkRunner class for rx/rx2

### PR DESCRIPTION
**Pull request by amilcar-andrade**

### CODE REVIEW

**Comment by amilcar-andrade** [comment]
It seems the change is binary incompatible but we are not using this class anymore ... What would be the best way to clean things up? 

Screen Shot 2020-04-19 at 4 49 09 PM

**Comment by pettermahlen** [comment]
We will simply have to keep it until we make a new major version. It's a bit bad, but not really terrible. (in case you haven't seen it, here's a great talk about that topic: https://www.youtube.com/watch?v=oyLBGkS5ICk)

**Comment by amilcar-andrade** [comment]
Thanks for explaining will close the PR

**Comment by togi** [comment]
This is not an unused class - it's a public API that users of mobius depend on. Eg. at Spotify we have at least 73 usages of it.

**Comment by amilcar-andrade** [comment]
Oh makes sense, I will add it to the RxJava3 PR.

**Pull request closed without merging**
