### PR TITLE
Fix #59, Gradle sync issue in Android Studio 3.3.2.

### LINKED ISSUE #59: Gradle sync issue in Android Studio 3.3.2
When I try to sync the downloaded Mobius project, my sync fails with the following error message.
```
ERROR: No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android
```

**Installed version of Android Studio**
```
Android Studio 3.3.2
Build #AI-182.5107.16.33.5314842, built on February 16, 2019
JRE: 1.8.0_152-release-1248-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6
```

I was able to fix this problem by changing the android build tools Gradle plugin version from `3.0.1` to `3.1.0`.

Can send a PR if required.

### PR DESCRIPTION
**Pull request by ragunathjawahar**

### CODE REVIEW

**Comment by pettermahlen** [comment]
Thanks for the PR!. Looks fine to me, except the build is failing because somehow build-tools 27.0.3 are requested, which is different than what is specified in the travis.yml file. Could you see if it works if you change to 27.0.3 there, or as a worse alternative, by applying the workaround suggested in https://github.com/travis-ci/travis-ci/issues/8874#issuecomment-350350607?

**Comment by ragunathjawahar** [comment]
No problem, I will look into this.

**Comment by ragunathjawahar** [comment]
@pettermahlen fixed by updating the build tools version in `travis.yml` file.

**Comment by pettermahlen** [comment]
Awesome, thanks!

**Pull request merged**
