### PR TITLE
NextMatchers + MobiusLoopBehaviorWithEventSources: Removes unnecessary 'else' clauses

### PR DESCRIPTION
**Pull request by amilcar-andrade**

### CODE REVIEW

**Comment by jeppes** [comment]
Closing this and https://github.com/spotify/mobius/pull/114. These changes do not tangibly improve the quality of the code and come down to personal opinion.

**Comment by jeppes** [comment]
Sorry, closing this was hasty. I will leave this re-open for discussion; but please make an argument for the changes.

**Comment by amilcar-andrade** [comment]
@jeppes, you mean besides readability?

**Comment by amilcar-andrade** [comment]
Either way, feel free to close both PRs

**Comment by jeppes** [comment]
Personally I find it less readable. It breaks symmetry and obscures the fact that a binary decision is being made. As for consistency, a search for `else` cases reveals several more explicit `else`s.

**Comment by amilcar-andrade** [comment]
@jeppes  FYI -> http://llvm.org/docs/CodingStandards.html#id39

**Pull request closed without merging**
