### PR TITLE
RxJava3: Port DiscardAfterDisposeConnectable

### PR DESCRIPTION
**Pull request by amilcar-andrade**

### CODE REVIEW

**Comment by sedovmik** [comment]
@amilcar-andrade Thank you for your PR. We'd like to wait with merging it because we are not fully sure that #112 is the actual root cause of crashes we see. Until we see the effect, we don't want merge #116

**Comment by amilcar-andrade** [comment]
@sedovmik any update on this?

**Comment by amilcar-andrade** [comment]
Closing, seems this is/was not that important to port over

**Comment by amilcar-andrade** [comment]
@sedovmik ready for re-review

**Review by sedovmik — APPROVED** [review]

**Pull request merged**
