### PR TITLE
RxMobius: Prefer package visibility over public for internal classes

### PR DESCRIPTION
**Pull request by amilcar-andrade**

### CODE REVIEW

**Comment by pettermahlen** [comment]
This is the same as #102, it can't be done until we make a new major version. At which point, we're planning on moving everything to a new namespace so that we don't in fact break existing usages.

**Comment by amilcar-andrade** [comment]
Thanks for explaining will close the PR

**Comment by amilcar-andrade** [comment]
@pettermahlen from the talk, should the classes then be called MergedTransformer2, and so on? 
and use the 2 implementation which is package protected, 🤔 ? 

Screen Shot 2020-04-20 at 3 19 48 PM

**Comment by pettermahlen** [comment]
I would think the point is that we don't want `MergedTransformer` in the publicly exposed namespace, so in the new namespace (`com.spotify.mobius2`, maybe), we won't include it. So in terms of the talk, I'm expecting us to publish a new artifact and new namespaces, and leave the current Mobius 1 artefact and namespaces around 'forever'. That means that Mobius 1 and 2 will be able to coexist in the same binary, and we won't be taking away functionality from users, while still publishing a new thing that we think is better.

**Pull request closed without merging**
